#!/bin/sh

#============================| INFO
# This file is part of a bigger project
# called archonpkg.
# It will shelter the functions to create
# packages with the extension .archon

# Script created by jean0t
# in 25/05/2024
# https://github.com/jean0t
#============================| GLOBAL VARIABLES
export pkg_extension="archon"

#============================| FUNCTIONS
CHECK_PKG() {
	pkg_name="$@"

	# verify the extension of the file
	if ! echo ! "$pkg_name" | grep -q "\b${pkgext}\b$"; then
		printf "%s\n" "The extension must be: ${pkg_extension}"
		return 1
	fi

	# verify spaces in the name of the package
	if echo "$pkg_name" | grep -qE "[[:space:]]+"; then
		printf "%s\n" "The name of the package has spaces"
		printf "%s\n" "Aborting operation." 
		return 1
	fi

	# verify if the number of version and build exists
	# by counting the number of dashes - used
	verification=`echo "${pkg_name}" | grep -o "-" | wc -l`
	if [ "$verification" -lt '2' ] || [ "$verification" -gt '2' ]; then
		printf "%s\n" "The format of the name must be:"
		printf "%s\n" "name-version-build.${pkg_extension}"
		return 1
	fi
	
	return 0
}

CREATE_PKG() {
	pkg_name="$1" # receive the name of the package

	if tar -cvf ../${pkg_name} .; then
		printf "%s\n" "The package was created in ../${pkg_name}"
		return 0
	else
		printf "%s\n" "The package ${pkg_name} was not created."
		exit 1
	fi
}

#============================| START
case "$1" in
	create|-c)
			shift
			if [ -z "$1" ]; then
				printf "%s\n" "No package was passed."
				exit 1
			fi
			CHECK_PKG "$@" || exit 1
			CREATE_PKG "$@"
		;;
esac

#============================| END
